version: "3.8"

services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - facebook_clone_net

  backend:
    depends_on:
      - mongodb
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - .:/workspace:cached
    networks:
      - facebook_clone_net

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    volumes:
      - .:/workspace:cached
    networks:
      - facebook_clone_net

volumes:
  mongodb_data_container:

networks:
  facebook_clone_net:
    name: facebook_clone_network
