version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile

    env_file:
      - ./frontend/.env
    volumes:
      - .:/workspace:cached

  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    volumes:
      - .:/workspace:cached
