version: "3.8"

services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  backend:
    depends_on:
      - mongodb
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    volumes:
      - .:/workspace:cached

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile

    env_file:
      - ./frontend/.env
    volumes:
      - .:/workspace:cached

volumes:
  mongodb_data_container:
